# Cloud Run service configuration for Gmail MCP Server
# This will deploy the Gmail MCP server on Google Cloud Run

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gmail-mcp-server
  annotations:
    cloud.google.com/location: us-central1
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/gmail-mcp-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: gmail-oauth-secrets
              key: client_id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: gmail-oauth-secrets
              key: client_secret
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi